/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author FAHAD_ISHAQ
 */
public class Add_Event extends javax.swing.JFrame {

    /**
     * Creates new form Add_Event
     */
    public Add_Event() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Description = new javax.swing.JTextField();
        event_date = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        event_name = new javax.swing.JTextField();
        add_event = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        var = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        shows = new javax.swing.JRadioButton();
        INFORMATIVE = new javax.swing.JRadioButton();
        conference = new javax.swing.JRadioButton();
        seminar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 210, -1));

        event_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_dateActionPerformed(evt);
            }
        });
        getContentPane().add(event_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 210, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 210, -1));

        event_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_nameActionPerformed(evt);
            }
        });
        getContentPane().add(event_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 210, -1));

        add_event.setBackground(new java.awt.Color(255, 255, 255));
        add_event.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add_event.setText("ADD EVENT");
        add_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_eventActionPerformed(evt);
            }
        });
        getContentPane().add(add_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 160, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EVENT DATE: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        var.setBackground(new java.awt.Color(255, 255, 255));
        var.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        var.setText("EVENT TYPE: ");
        getContentPane().add(var, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TICKET PRICE: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("EVENT DESCRIPTION: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, 20));

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel1.setText("BACK");
        cancel1.setSelected(true);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 160, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("EVENT NAME: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        buttonGroup1.add(shows);
        shows.setText("SHOWS AND EVENTS");
        getContentPane().add(shows, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        buttonGroup1.add(INFORMATIVE);
        INFORMATIVE.setText("INFORMATIVE");
        getContentPane().add(INFORMATIVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));

        buttonGroup1.add(conference);
        conference.setText("CONFERENCE");
        conference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferenceActionPerformed(evt);
            }
        });
        getContentPane().add(conference, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        buttonGroup1.add(seminar);
        seminar.setText("SEMINAR");
        getContentPane().add(seminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/ADD EVENT.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void event_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_dateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_event_dateActionPerformed

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void event_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_nameActionPerformed

    private void add_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_eventActionPerformed
        // TODO add your handling code here:
        String name=event_name.getText();
        //Long cnic=Long.parseLong(CNIC);
        String date=event_date.getText();
        String type="";
        int sid=1;
        
        if (seminar.isSelected()){
            type+="Seminar";
            
        }
        else if (shows.isSelected()){
            type+="Shows and Events";
        }
        else if (conference.isSelected()){
            type+="Conference";
            
        }
        else if (INFORMATIVE.isSelected()){
            type+="Informative";
            
        }
        String event_description=Description.getText();
        String event_price=price.getText();
  
      
    
            int b=0;
            
        try 
        {
            //JavaConnection j1=new JavaConnection();
            Class.forName("oracle.jdbc.OracleDriver");
			  
			//step2 create  the connection object  jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
			  
			//step3 create the statement object  
			//Statement s=con.createStatement();  
            String[ ][ ] row=new String[11][11];
            Statement s=con.createStatement();  
            
            ResultSet rs=s.executeQuery("SELECT Event_ID from Admin_Events");
            
         
            
            while (rs.next())
            {
               String a=String.valueOf(rs.getLong("Event_ID"));
               b=Integer.parseInt(a);
               
               if (b==sid){
                   continue;
               }else{
                   b++;  
               }
           

            }
                 sid=b; 
            con.close();
        }  
			  
	catch(Exception e){ 
				JOptionPane.showMessageDialog(null, e);
                                
			}  
        
        System.out.println("b:" + sid);

        
          try 
        {
            //JavaConnection j1=new JavaConnection();
            Class.forName("oracle.jdbc.OracleDriver");
			  
			//step2 create  the connection object  jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
            Statement s=con.createStatement();
            System.out.println("here");
             

            String k= "INSERT into Admin_Events(event_id,event_name,event_description,event_date,event_type,event_price) values('"+(sid+1)+"','"+name+"','"+event_description+"','"+date+"','"+type+"','"+event_price+"')";
            
            System.out.println("sfjksdf");
            s.executeUpdate(k);
              JOptionPane.showMessageDialog(null, "EVENT ADDED"); 
        
        }
        catch(Exception e){
            	JOptionPane.showMessageDialog(null, e);
            }
        
        
        
        
                

    }//GEN-LAST:event_add_eventActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        dispose();
        admin_events cust=new admin_events();
        cust.setLocationRelativeTo(null);
        cust.setVisible(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void conferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conferenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Event().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Description;
    private javax.swing.JRadioButton INFORMATIVE;
    private javax.swing.JButton add_event;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel1;
    private javax.swing.JRadioButton conference;
    private javax.swing.JTextField event_date;
    private javax.swing.JTextField event_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField price;
    private javax.swing.JRadioButton seminar;
    private javax.swing.JRadioButton shows;
    private javax.swing.JLabel var;
    // End of variables declaration//GEN-END:variables
}
