/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;
import java.sql.*;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    
import java.util.Random;

public class Book_Room extends javax.swing.JFrame {

    Customer_Login cust; 
  
    public Book_Room() {

        initComponents();
         try 
        {
            //JavaConnection j1=new JavaConnection();
            Class.forName("oracle.jdbc.OracleDriver");
			  
			//step2 create  the connection object  jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
         Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

			
            String[ ][ ] row=new String[8][8];
            Statement s=con.createStatement(); 
            String aa="false";
            
            ResultSet rs=s.executeQuery("SELECT * from room where room.is_booked='"+aa+"'");
             System.out.println("here");
             
            while (rs.next())
            {
                
               String a=String.valueOf(rs.getLong("Room_id"));
               
               String aF=String.valueOf(rs.getString("Room_Type"));
               String Ns=String.valueOf(rs.getString("is_Booked"));
               
               String Nsfa=String.valueOf(rs.getLong("room_price"));
               String desc=String.valueOf(rs.getString("Descriptions"));
               String tbdata[]={a,aF,Ns,Nsfa,desc};
               DefaultTableModel table3=(DefaultTableModel)table.getModel();
               table3.addRow(tbdata);
               
            }
            con.close();
//            JOptionPane.showMessageDialog(null, "Search Found");
        }  
			  
	catch(Exception e){ 
				JOptionPane.showMessageDialog(null, e);
                                
			}  
            
    }
    
   
    private void all_rooms(){
        try 
        {
            //JavaConnection j1=new JavaConnection();
            Class.forName("oracle.jdbc.OracleDriver");
			  
			//step2 create  the connection object  jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
         Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

			
            String[ ][ ] row=new String[8][8];
            Statement s=con.createStatement(); 
            String aa="false";
            
            ResultSet rs=s.executeQuery("SELECT * from room where room.is_booked='"+aa+"'");
             System.out.println("here");
             
            while (rs.next())
            {
                
               String a=String.valueOf(rs.getLong("Room_id"));
               
               String aF=String.valueOf(rs.getString("Room_Type"));
               String Ns=String.valueOf(rs.getString("is_Booked"));
               
               String Nsfa=String.valueOf(rs.getLong("room_price"));
               String desc=String.valueOf(rs.getString("Descriptions"));
               String tbdata[]={a,aF,Ns,Nsfa,desc};
               DefaultTableModel table3=(DefaultTableModel)table.getModel();
               table3.addRow(tbdata);
               
            }
            con.close();
//            JOptionPane.showMessageDialog(null, "Search Found");
        }  
			  
	catch(Exception e){ 
				JOptionPane.showMessageDialog(null, e);
                                
			}  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        stay = new javax.swing.JTextField();
        book_room = new javax.swing.JButton();
        room_num = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancel1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Is_Booked", "Price", "Room Description"
            }
        ));
        table.setEnabled(false);
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 850, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Enter Stay Duration: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, 40));

        stay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayActionPerformed(evt);
            }
        });
        getContentPane().add(stay, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 200, -1));

        book_room.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        book_room.setText("BOOK ROOM");
        book_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_roomActionPerformed(evt);
            }
        });
        getContentPane().add(book_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 160, 50));

        room_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_numActionPerformed(evt);
            }
        });
        getContentPane().add(room_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Enter Room Number: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, 50));

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel1.setText("BACK");
        cancel1.setSelected(true);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/booking_1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stayActionPerformed

    private void book_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_roomActionPerformed
         String room_numm="";
         Customer_Login c=new Customer_Login();
        int ss= c.id();
         
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
   LocalDateTime now = LocalDateTime.now();  
   
         
         System.out.println("id:"+ c.id());
         
         
         
        try 
        {
           	 String days=stay.getText();
                 room_numm=room_num.getText();
                 
             Class.forName("oracle.jdbc.OracleDriver");
			  
	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
            Statement s=con.createStatement();
            
            String l= "INSERT into BOOK(Room_Room_id,Customer_cust_id,number_of_days_of_stay,check_in) values('"+room_numm+"','"+ss+"','"+days+"','"+now+"')";
            s.executeUpdate(l);
         
            
            
            
              JOptionPane.showMessageDialog(null, "Room Booked Successfully"); 
              
            
        }  
        
        catch(Exception e){ 
				JOptionPane.showMessageDialog(null, e);
                                
			}  
	
              
               try 
        {
            
            
            //updating Room Info
            Class.forName("oracle.jdbc.OracleDriver");
	 
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
             java.sql.Statement s=con.createStatement();
                String condition="true";
                System.out.println("hhhhh");
                 String l= "UPDATE Room set is_booked='"+condition+"'where room_id='"+room_numm+ "'";

            s.executeUpdate(l);
         
        }
        catch(Exception e){
            	JOptionPane.showMessageDialog(null, e);
            }
               
               
               
               //assigning the customer to the Employee
                
               
               String emp_id="";
               
                 try{
                   
                   //Assigning the room service
            
                       Class.forName("oracle.jdbc.OracleDriver");
	 
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
             java.sql.Statement s=con.createStatement();
                String condition="true";
                System.out.println("hhhhh");
                
                 String l= "select emp_id from staff where emp_job='MANAGEMENT' and emp_id=105";
                 
//                         + "rder by dbms_random.value FETCH FIRST 1 ROWS ONLY";
                ResultSet rs= s.executeQuery(l);
            while (rs.next()){
                
                emp_id+=String.valueOf(rs.getString("emp_id"));

            }
            
            
            String k= "INSERT into manage_customers(staff_emp_id,customer_cust_id) values('"+emp_id+"','"+ss+"')";
            
                    s.executeUpdate(k);
           
                     System.out.println("emp"+ emp_id);
 
                   
                   
                   
               }
               catch (Exception e){
                   
                   
                   System.out.println("Exception: "+e.toString());
               }
          
    }//GEN-LAST:event_book_roomActionPerformed

    private void room_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_numActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        dispose();
        Customer_Frame cust=new Customer_Frame();
        cust.setLocationRelativeTo(null);
        cust.setVisible(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book_room;
    private javax.swing.JButton cancel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField room_num;
    private javax.swing.JTextField stay;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
