/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import javax.swing.JOptionPane;

/**
 *
 * @author FAHAD_ISHAQ
 */
public class Customer_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Frame
     */
    public Customer_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Edit_Profile = new javax.swing.JButton();
        Give_Laundry = new javax.swing.JButton();
        food = new javax.swing.JButton();
        Book_Room = new javax.swing.JButton();
        Add_Review = new javax.swing.JButton();
        Invoice = new javax.swing.JButton();
        Book_Event = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit_Profile.setBackground(new java.awt.Color(0, 204, 102));
        Edit_Profile.setText("EDIT PROFILE");
        Edit_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ProfileActionPerformed(evt);
            }
        });
        getContentPane().add(Edit_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 110, -1));

        Give_Laundry.setBackground(new java.awt.Color(0, 204, 102));
        Give_Laundry.setText("GIVE LAUNDRY");
        Give_Laundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Give_LaundryActionPerformed(evt);
            }
        });
        getContentPane().add(Give_Laundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 130, -1));

        food.setBackground(new java.awt.Color(0, 204, 102));
        food.setText("ORDER FOOD");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        getContentPane().add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 110, -1));

        Book_Room.setBackground(new java.awt.Color(0, 204, 102));
        Book_Room.setText("BOOK ROOM");
        Book_Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_RoomActionPerformed(evt);
            }
        });
        getContentPane().add(Book_Room, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        Add_Review.setBackground(new java.awt.Color(0, 204, 102));
        Add_Review.setText("ADD REVIEW");
        Add_Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ReviewActionPerformed(evt);
            }
        });
        getContentPane().add(Add_Review, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 110, -1));

        Invoice.setBackground(new java.awt.Color(0, 204, 102));
        Invoice.setText("CHECK-OUT");
        Invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(Invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 130, -1));

        Book_Event.setBackground(new java.awt.Color(0, 204, 102));
        Book_Event.setText("BOOK EVENT");
        Book_Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_EventActionPerformed(evt);
            }
        });
        getContentPane().add(Book_Event, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 110, -1));

        checkout.setBackground(new java.awt.Color(0, 204, 102));
        checkout.setText("PAYMENT");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });
        getContentPane().add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 130, -1));

        logout.setBackground(new java.awt.Color(0, 204, 102));
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/customer_options.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Edit_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ProfileActionPerformed
        
        dispose();
        
       Update_Profile g=new Update_Profile();
         g.setLocationRelativeTo(null);
           g.setVisible(true);
  
    }//GEN-LAST:event_Edit_ProfileActionPerformed

    private void Give_LaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Give_LaundryActionPerformed
       dispose();
        Add_Laundry g=new Add_Laundry();
           g.setLocationRelativeTo(null);
           g.setVisible(true);
        
        
    }//GEN-LAST:event_Give_LaundryActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        dispose();
        
        order_food g=new order_food();
        g.setLocationRelativeTo(null);
           g.setVisible(true);
    }//GEN-LAST:event_foodActionPerformed

    private void Book_RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_RoomActionPerformed
      
            
           Book_Room g =new Book_Room();
           g.setLocationRelativeTo(null);
           g.setVisible(true);
    }//GEN-LAST:event_Book_RoomActionPerformed

    private void Add_ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ReviewActionPerformed
        
         Add_Reviews g =new Add_Reviews();
        g.setLocationRelativeTo(null);
           g.setVisible(true);
    }//GEN-LAST:event_Add_ReviewActionPerformed

    private void InvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceActionPerformed
            
        
        
        dispose();    
            Invoice g=new Invoice();
          g.setLocationRelativeTo(null);
           g.setVisible(true);
           

    }//GEN-LAST:event_InvoiceActionPerformed

    private void Book_EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_EventActionPerformed
       
        dispose();
        
            Book_Event g =new Book_Event();

          g.setLocationRelativeTo(null);
           g.setVisible(true);
    }//GEN-LAST:event_Book_EventActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        
        dispose(); 
         Payment g=new Payment();
          g.setLocationRelativeTo(null);
           g.setVisible(true);
       
    }//GEN-LAST:event_checkoutActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       dispose();
       
        Customer_Login g=new Customer_Login();
          g.setLocationRelativeTo(null);
           g.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Review;
    private javax.swing.JButton Book_Event;
    private javax.swing.JButton Book_Room;
    private javax.swing.JButton Edit_Profile;
    private javax.swing.JButton Give_Laundry;
    private javax.swing.JButton Invoice;
    private javax.swing.JButton checkout;
    private javax.swing.JButton food;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
