/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAHAD_ISHAQ
 */
public class staff_info_complete extends javax.swing.JFrame {

    /**
     * Creates new form staff_info_complete
     */
    public staff_info_complete() {
        initComponents();
    }
    
    public void all_info(){ 
        try
        {
         
            Class.forName("oracle.jdbc.OracleDriver");

                java.sql.Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

            String[][] row=new String[4][6];
            java.sql.Statement s=con.createStatement();

            java.sql.ResultSet rs=s.executeQuery("select staff.emp_id, count(manage_customers.staff_emp_id) as staff, staff.emp_name, staff.emp_cnic from manage_customers cross join staff where manage_customers.staff_emp_id=staff.emp_id\n" +
" group by emp_id, staff.emp_name, staff.emp_cnic");
            

            while (rs.next())
            {
                String k=String.valueOf(rs.getString("emp_id"));
                
                String Name=String.valueOf(rs.getString("emp_Name"));
                String Address=String.valueOf(rs.getString("emp_cnic"));
                String Gender=String.valueOf(rs.getString("staff"));
          

                String tbdata[]={k,Name,Address,Gender};

                DefaultTableModel table3=(DefaultTableModel)table.getModel();

                table3.addRow(tbdata);

            }
            con.close();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel1 = new javax.swing.JButton();
        all = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        find = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel1.setText("BACK");
        cancel1.setSelected(true);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, 50));

        all.setBackground(new java.awt.Color(255, 255, 255));
        all.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        all.setText("VIEW TOTAL CUSTOMERS");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        getContentPane().add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 180, 50));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Search by ID: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee CNIC", "Number Of Customers Managing"
            }
        ));
        table.setEnabled(false);
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 760, 290));

        find.setBackground(new java.awt.Color(255, 255, 255));
        find.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        find.setText("Find");
        find.setSelected(true);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 60, -1));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setText("Clear");
        clear.setSelected(true);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/management.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        dispose();
        admin_employee cust=new admin_employee();
        cust.setLocationRelativeTo(null);
        cust.setVisible(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed

        table.setModel(new DefaultTableModel(null,new String[]{"Employee ID","Employee Name","Employee CNIC", "Number Of Customers Managing"}));
        all_info();
        all.setEnabled(false);
        
        

    }//GEN-LAST:event_allActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        
        int kk=0; 
        String name=""; 
        
   table.setModel(new DefaultTableModel(null,new String[]{"Employee Name","Customer ID","Customer Name", "Customer CNIC"}));

        
        try{
            
            Class.forName("oracle.jdbc.OracleDriver");

	    java.sql.Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

            java.sql.Statement s=con.createStatement();

            java.sql.ResultSet rs=s.executeQuery("select manage_customers.staff_emp_id, staff.emp_name from manage_customers cross join staff where staff.emp_id=manage_customers.staff_emp_id and staff_emp_id='"+id.getText()+"'");
           
            while (rs.next())
            {
                name+=String.valueOf(rs.getString("emp_name"));
                kk++;
                
            }
            
            
            
        }catch (Exception e) {
   JOptionPane.showMessageDialog(null,e);

        }
        if (kk!=0){ 
        
         try
        {
         
            Class.forName("oracle.jdbc.OracleDriver");

                java.sql.Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

            String[][] row=new String[4][6];
            java.sql.Statement s=con.createStatement();

            java.sql.ResultSet rs=s.executeQuery("select customer.cust_id, customer.cust_name, customer.cust_cnic from customer cross join \n" +
"manage_customers where customer.cust_id=manage_customers.customer_cust_id and manage_customers.staff_emp_id='"+id.getText()+"'order by customer.cust_id");
            
            
            while (rs.next())
            {
                String k=String.valueOf(rs.getString("cust_id"));  
                String Name=String.valueOf(rs.getString("cust_Name"));
                String Address=String.valueOf(rs.getString("cust_cnic"));
//                String Gender=String.valueOf(rs.getString("staff"));
          

                String tbdata[]={name,k,Name,Address};

                DefaultTableModel table3=(DefaultTableModel)table.getModel();

                table3.addRow(tbdata);

            }
            con.close();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
         
        }
        else{
            
               JOptionPane.showMessageDialog(null, "Record Not Found");

        }
    
        
        
        
        
    }//GEN-LAST:event_findActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        clear.setEnabled(true);
        all.setEnabled(true);
        table.setModel(new DefaultTableModel(null,new String[]{"Employee ID","Employee Name","Employee CNIC", "Number Of Customers Managing"}));
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_info_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_info_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_info_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_info_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_info_complete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton clear;
    private javax.swing.JButton find;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
