/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author FAHAD_ISHAQ
 */
public class Update_Room extends javax.swing.JFrame {

    /**
     * Creates new form Update_Room
     */
    public Update_Room() {
        initComponents();
       
    }
    
    public void set_text(String num){
        
             try 
        {
            Class.forName("oracle.jdbc.OracleDriver");
	 
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
             java.sql.Statement s=con.createStatement();

            
            java.sql.ResultSet rs=s.executeQuery("select * from Room where room_id='"+num+"'");
            
            while (rs.next())
            {
              
               String typee=String.valueOf(rs.getString("room_type"));
               String pricee=String.valueOf(rs.getString("room_price"));
               String desc=String.valueOf(rs.getString("descriptions"));
                    price.setText(pricee);
               if (typee.equals("Single Bed Room")){
                  
                   single.setSelected(true);
               }
               else if (typee.equals("Double Bed Room")){
                  
                   two.setSelected(true);
                   
               }else if (typee.equals("Studio Room")){
                   studio.setSelected(true);
               }else if (typee.equals("Triple Bed Room")){
                   triple.setSelected(true);
                   
               }
               else if (typee.equals("Quad Bed Room")){
                   quad.setSelected(true);
               }
              
            price.setText(pricee);
           descii.setText(desc);
           
            
            
            }
            
            
        }
        catch(Exception e){ 
				JOptionPane.showMessageDialog(null, "No Record");
                                
			}  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descii = new javax.swing.JTextArea();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        cancel1 = new javax.swing.JButton();
        single = new javax.swing.JRadioButton();
        two = new javax.swing.JRadioButton();
        studio = new javax.swing.JRadioButton();
        triple = new javax.swing.JRadioButton();
        quad = new javax.swing.JRadioButton();
        find = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Room Type: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Price: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 210, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Description: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        descii.setColumns(20);
        descii.setRows(5);
        jScrollPane1.setViewportView(descii);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 240, -1));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        update.setText("UPDATE ROOM");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 160, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Search By Room ID: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 40));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 300, -1));

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel1.setText("BACK");
        cancel1.setSelected(true);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, 50));

        buttonGroup1.add(single);
        single.setText("Single Bed Room");
        getContentPane().add(single, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        buttonGroup1.add(two);
        two.setText("Double Room");
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 100, -1));

        buttonGroup1.add(studio);
        studio.setText("Studio Room");
        studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studioActionPerformed(evt);
            }
        });
        getContentPane().add(studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        buttonGroup1.add(triple);
        triple.setText("Triple Room");
        getContentPane().add(triple, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, -1));

        buttonGroup1.add(quad);
        quad.setText("Quad Room");
        getContentPane().add(quad, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, -1, -1));

        find.setBackground(new java.awt.Color(255, 255, 255));
        find.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        find.setText("Find");
        find.setSelected(true);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 60, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/ROOMS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
       
          String pricee=price.getText();
        String type="";
        if (single.isSelected()){
            type+="Single Bed Room";
            
        }else if (two.isSelected()){
            type+="Double Bed Room";
            
        }else if (studio.isSelected()){
            type+="Studio Room";
            
        }else if(triple.isSelected()){
            type+="Triple Bed Room";
            
        }else if (quad.isSelected()){
            type+="Quad Bed Room";
            
        }
        String d=descii.getText();
        
             try 
        {
            //JavaConnection j1=new JavaConnection();
            Class.forName("oracle.jdbc.OracleDriver");
			  
			//step2 create  the connection object  jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
	      Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");
             java.sql.Statement s=con.createStatement();
//            String p= "UPDATE ADMIN set CNIC='"+cnic+"',Admin_Name='"+s1+"',address='"+s2+"',gender='"+s3+"',ph_no='"+s4+"',Admin_email='"+s5+"',Admin_password='"+s6+"'where CNIC='"+CNIC+ "'";
            String l= "UPDATE Room set room_price='"+pricee+"',room_type='"+type+"',descriptions='"+d+"' where room_id='"+id.getText()+ "'";

            s.executeUpdate(l);
            JOptionPane.showMessageDialog(null,"ROOM UPDATED SUCCESSFULY");
        
        }
        catch(Exception e){
            	JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_updateActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        dispose();
        admin_rooms cust=new admin_rooms();
        cust.setLocationRelativeTo(null);
        cust.setVisible(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studioActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
                set_text(id.getText()); 
                
    }//GEN-LAST:event_findActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel1;
    private javax.swing.JTextArea descii;
    private javax.swing.JButton find;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JRadioButton quad;
    private javax.swing.JRadioButton single;
    private javax.swing.JRadioButton studio;
    private javax.swing.JRadioButton triple;
    private javax.swing.JRadioButton two;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
