/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet; 



/**
 *
 * @author FAHAD_ISHAQ
 */
public class View_Rooms extends javax.swing.JFrame {

    /**
     * Creates new form View_Rooms
     */
    public View_Rooms() {
        initComponents();
    }
    
     private void all_rooms(){
        try 
        {
            //JavaConnection j1=new JavaConnection();
            Class.forName("oracle.jdbc.OracleDriver");
			  
			//step2 create  the connection object  jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
         Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

			
            String[ ][ ] row=new String[8][8];
            Statement s=con.createStatement();  
            
            ResultSet rs=s.executeQuery("SELECT * from ROOM");
             System.out.println("here");
            while (rs.next())
            {
               String a=String.valueOf(rs.getLong("Room_id"));
               String aF=String.valueOf(rs.getString("Room_Type"));
               String Ns=String.valueOf(rs.getString("is_Booked"));
               
               String Nsfa=String.valueOf(rs.getLong("room_price"));
               String desc=String.valueOf(rs.getString("Descriptions"));
               String tbdata[]={a,aF,Ns,Nsfa,desc};
               DefaultTableModel table3=(DefaultTableModel)table.getModel();
               table3.addRow(tbdata);
               
            }
            con.close();
//            JOptionPane.showMessageDialog(null, "Search Found");
        }  
			  
	catch(Exception e){ 
				JOptionPane.showMessageDialog(null, e);
                                
			}  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        find = new javax.swing.JButton();
        clearr = new javax.swing.JButton();
        all = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Price", "Room Description", "Is_Booked"
            }
        ));
        table.setEnabled(false);
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 930, 320));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Search by Room Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 20));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 150, -1));

        find.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        find.setText("Find");
        find.setSelected(true);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        clearr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearr.setText("Clear");
        clearr.setSelected(true);
        clearr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearrActionPerformed(evt);
            }
        });
        getContentPane().add(clearr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        all.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        all.setText("View All");
        all.setSelected(true);
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        getContentPane().add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 160, 50));

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel1.setText("BACK");
        cancel1.setSelected(true);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/room.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
       
        
        
        table.setModel(new DefaultTableModel(null,new String[]{"Room Number","Room Type","Price","Room Description","Is_Booked"}));
 
        
        String r_id=id.getText();
        int check=0;
        
         try
        {
            Class.forName("oracle.jdbc.OracleDriver");

	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

            String[][] row=new String[4][6];
            Statement s=con.createStatement();
            
            
            java.sql.ResultSet rs=s.executeQuery("select * from Room where room_id='"+r_id+"' order by room_id");

            while (rs.next())
            {
                  String k=String.valueOf(rs.getString("room_id"));
                String CNIC_n=String.valueOf(rs.getString("room_type"));
                String Name=String.valueOf(rs.getString("room_price"));
                String Address=String.valueOf(rs.getString("descriptions"));
                String Gender=String.valueOf(rs.getString("IS_Booked"));
              
                check++;
                
                String tbdata[]={k,CNIC_n,Name,Address,Gender};
                
                
                DefaultTableModel table3=(DefaultTableModel)table.getModel();

                table3.addRow(tbdata);

            }
            con.close();
            
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
         
         if (check==0){
                         JOptionPane.showMessageDialog(null, "NO RECORD FOUND");

             
         }
        
        
        
     
     
    }//GEN-LAST:event_findActionPerformed

    private void clearrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearrActionPerformed
            all.setSelected(true);
        all.setEnabled(true);
        table.setModel(new DefaultTableModel(null,new String[]{"Room Number","Room Type","Price","Room Description","Is_Booked"}));
    }//GEN-LAST:event_clearrActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
      all.setSelected(false);
        all.setEnabled(false);
        all_rooms();
        
    }//GEN-LAST:event_allActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        dispose();
        admin_rooms cust=new admin_rooms();
        cust.setLocationRelativeTo(null);
        cust.setVisible(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton clearr;
    private javax.swing.JButton find;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
