/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        
        
/**
 *
 * @author FAHAD_ISHAQ
 */
public class View_Food extends javax.swing.JFrame {

    /**
     * Creates new form View_Food
     */
    public View_Food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        find = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        view_all = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food_ID", "Food Name", "Food Type", "Price"
            }
        ));
        table.setEnabled(false);
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 670, 270));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Search by ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 404, -1, 30));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 150, -1));

        find.setBackground(new java.awt.Color(255, 255, 255));
        find.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        find.setText("Find");
        find.setSelected(true);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setText("Clear");
        clear.setSelected(true);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));

        view_all.setBackground(new java.awt.Color(255, 255, 255));
        view_all.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        view_all.setText("VIEW ALL");
        view_all.setSelected(true);
        view_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_allActionPerformed(evt);
            }
        });
        getContentPane().add(view_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 160, 50));

        cancel1.setBackground(new java.awt.Color(255, 255, 255));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel1.setText("BACK");
        cancel1.setSelected(true);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/SEARCH_FPOOD.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        
        String CNIC=id.getText();
        
        
        
        
        table.setModel(new DefaultTableModel(null,new String[]{"Food_ID","Food Name","Food Description","Price"}));
 
        int check=0;
        
         try
        {
            Class.forName("oracle.jdbc.OracleDriver");

	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

            String[][] row=new String[4][6];
            Statement s=con.createStatement();
            
            
            java.sql.ResultSet rs=s.executeQuery("select food_id,food_name,food_type,food_price from admin_food where food_id='"+CNIC+"'");

            while (rs.next())
            {
                  String k=String.valueOf(rs.getString("food_id"));
                String CNIC_n=String.valueOf(rs.getString("food_name"));
                String Name=String.valueOf(rs.getString("food_type"));
                String pric=String.valueOf(rs.getString("food_price"));
                
                check++;
                
                String tbdata[]={k,CNIC_n,Name,pric};
                
                
                DefaultTableModel table3=(DefaultTableModel)table.getModel();

                table3.addRow(tbdata);

            }
            con.close();
            
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
         
         if (check==0){
                         JOptionPane.showMessageDialog(null, "NO RECORD FOUND");

             
         }
       
        
        
        
     
       
    }//GEN-LAST:event_findActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        view_all.setSelected(true);
        view_all.setEnabled(true);
        id.setText(null);
        table.setModel(new DefaultTableModel(null,new String[]{"Food_ID","Food Name","Food Type","Price"}));
    }//GEN-LAST:event_clearActionPerformed

    private void view_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_allActionPerformed
        // TODO add your handling code here:
//        view_all.setSelected();
        view_all.setEnabled(false);
        id.setText(null);
        table.setModel(new DefaultTableModel(null,new String[]{"Food_ID","Food Name","Food Type","Price"}));
        
        
        
        
        
          int check=0;
        
         try
        {
            Class.forName("oracle.jdbc.OracleDriver");

	    Connection con=DriverManager.getConnection("jdbc:oracle:thin:TWITTER/twitter@//localhost:1521/orclpdb");

            String[][] row=new String[4][6];
            Statement s=con.createStatement();
            
            
            java.sql.ResultSet rs=s.executeQuery("select food_id,food_name,food_type,food_price from admin_food");

            while (rs.next())
            {
                  String k=String.valueOf(rs.getString("food_id"));
                String CNIC_n=String.valueOf(rs.getString("food_name"));
                String Name=String.valueOf(rs.getString("food_type"));
                String pric=String.valueOf(rs.getString("food_price"));
                
                check++;
                
                String tbdata[]={k,CNIC_n,Name,pric};
                
                
                DefaultTableModel table3=(DefaultTableModel)table.getModel();

                table3.addRow(tbdata);

            }
            con.close();
            
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
         
         if (check==0){
                         JOptionPane.showMessageDialog(null, "NO RECORD FOUND");

             
         }
        
        
        
        
    }//GEN-LAST:event_view_allActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        dispose();
        admin_food cust=new admin_food();
        cust.setLocationRelativeTo(null);
        cust.setVisible(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel1;
    private javax.swing.JButton clear;
    private javax.swing.JButton find;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JButton view_all;
    // End of variables declaration//GEN-END:variables
}
